name: Build RandomCall

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'  # 请根据你的项目实际版本调整

    - name: Restore dependencies
      run: dotnet restore RandomCall.sln

    - name: Build RandomCall
      run: dotnet build RandomCall.sln --configuration Release --no-restore

    - name: Test Output
      run: dotnet test RandomCall.sln --no-restore --verbosity normal

    - name: Upload .exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: RandomCall-exe
        path: '**/bin/Release/**/*.exe'
