name: Build RandomCall

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '4.7.2'

    - name: Restore dependencies
      run: dotnet restore RandomCall-NET.sln

    - name: Build RandomCall
      run: dotnet build RandomCall-NET.sln --configuration Release --no-restore

    - name: Test Output
      run: dotnet test RandomCall-NET.sln --no-restore --verbosity normal

    - name: Upload .exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: RandomCall-exe
        path: '**/bin/Release/**/*.exe'
